---
title: "QA.2"
author: "Issac Lee"  
date: "`r format(Sys.Date())`"
output:  
  html_document:  
    keep_md: true 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## [QA.2](https://www.facebook.com/groups/krstudy/permalink/766011580239783)
안녕하세요.
R을 배우는 중인데 질문이 있어서 올립니다.

2n개의 수를 만들어서 정수와 정수가 아닌 수로 구분한 후 각각의 mean이나 median을 구하는 문제인데요. 제가 짠 코드에서 저는 mean을 디폴트로 해놨는데 왜 mysplit(x,3)을 치면 바로 mean이 안뜰까요?

mysplit(x,n)만 쳐서 mean이 뜨게 하려면 코드에서 어느 부분을 수정해야 할까요?

```{r eval=FALSE}
mysplit <- function(x, n, method= "mean") {
x1<-sample(n,size=n,replace=T)
x2<-rnorm(n)
x<-c(x1,x2)
x
a<-NULL
b<-NULL
for (i in x) {
if (i %% 1 == 0) a<-c(a,i) else b<-c(b,i)
}
print(a)
print(b)
return(c(method(a),method(b)))
}
```

```{r eval=FALSE}
mysplit(x,3)
mysplit(x,3,median)
```


## Answer
[Functional programming(FP)](http://adv-r.had.co.nz/Functional-programming.html)을 적용해서 짜기 좋은 상황이다. FP는 코드의 중복을 상당히 많이 줄일 수 있는 효율적인 코딩이 가능하다.

다음은 정수와 소수가 섞여있는 임의의 벡터에 대하여, 정수부분과 소수부분을 원하는 연산을 사용하여 각각 계산하는 함수를 만들어주는 함수을 만드는 방법이다.

### 임의의 벡터 발생
```{r}
# generate random vector
n <- 10
a <- sample(n, 2*n, replace = TRUE)
r.index <- sample(2*n, n)
a[r.index] <- a[r.index] + runif(n)
a    
```

```{r warning=FALSE, message=FALSE}
mysplit <- function(f){
  function(x){
    c(f(x[x %% 1 == 0]),
      f(x[x %% 1 != 0]))
  }
}
```

만들어진 함수의 사용법은 다음과 같다.
```{r}
mysplit.median <- mysplit(median)
mysplit.median(a)

mysplit.mean <- mysplit(mean)
mysplit.mean(a)

mysplit.sum <- mysplit(sum)
mysplit.sum(a)

```

